#!/bin/bash

set -e

IFS=/ read -r USER REPO <<< "$1"

nix-prefetch-url --unpack "https://github.com/$USER/$REPO/archive/$2.tar.gz"  \
  | tr -d \\n \
  | pbcopy

echo "Copied SHA-256 hash to clipboard!"
